"""lineage cluster_run_id nullable for expert decisions

Revision ID: ff57f3ac56e7
Revises: 21d342758d70
Create Date: 2026-09-13 20:43:06.059385+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

revision: str = 'ff57f3ac56e7'
down_revision: str | None = '21d342758d70'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('technology_lineage', 'cluster_run_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('technology_lineage', 'cluster_run_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
