"""initial schema

Revision ID: 21d342758d70
Revises: 
Create Date: 2026-09-13 15:31:10.331767+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '21d342758d70'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector должен существовать до создания таблиц с колонками VECTOR.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('normalized_query', sa.Text(), nullable=True),
    sa.Column('query_language', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('coverage_confidence', sa.Float(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=True),
    sa.Column('result_snapshot_id', sa.String(length=128), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_jobs'))
    )
    op.create_index('ix_jobs_status', 'analysis_jobs', ['status', 'requested_at'], unique=False)
    op.create_table('cluster_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('embedding_model_version', sa.String(length=128), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('documents_count', sa.Integer(), nullable=True),
    sa.Column('clusters_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cluster_runs'))
    )
    op.create_table('expert_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=64), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('labeling_round', sa.String(length=64), nullable=True),
    sa.Column('point_in_time_date', sa.Date(), nullable=True),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expert_feedback'))
    )
    op.create_index('ix_feedback_object', 'expert_feedback', ['object_type', 'object_id'], unique=False)
    op.create_index('ix_feedback_round', 'expert_feedback', ['labeling_round'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('benchmark_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('kind', 'version', name='uq_model_kind_version')
    )
    op.create_table('peer_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('taxonomy_type', sa.String(length=64), nullable=False),
    sa.Column('external_code', sa.String(length=128), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('reference_population_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_population_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['peer_groups.id'], name=op.f('fk_peer_groups_parent_id_peer_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_peer_groups')),
    sa.UniqueConstraint('version', 'taxonomy_type', 'external_code', name='uq_peer_group_code')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('license_status', sa.String(length=32), nullable=False),
    sa.Column('license_type', sa.String(length=128), nullable=True),
    sa.Column('license_checked_at', sa.Date(), nullable=True),
    sa.Column('license_owner', sa.String(length=255), nullable=True),
    sa.Column('allows_fulltext_storage', sa.Boolean(), nullable=False),
    sa.Column('allows_embedding_storage', sa.Boolean(), nullable=False),
    sa.Column('allows_rag_use', sa.Boolean(), nullable=False),
    sa.Column('allows_derivative_analytics', sa.Boolean(), nullable=False),
    sa.Column('attribution_required', sa.Boolean(), nullable=False),
    sa.Column('requires_credentials', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=True),
    sa.Column('weekly_volume_cap_bytes', sa.BigInteger(), nullable=True),
    sa.Column('evidence_weight', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('code', name=op.f('uq_sources_code'))
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority_date', sa.Date(), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('grant_date', sa.Date(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_revision', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_storage_key', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('embedding_model_version', sa.String(length=128), nullable=True),
    sa.Column('external_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('institutions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_documents_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_documents_source_external')
    )
    op.create_index('ix_documents_available_from', 'documents', ['available_from'], unique=False)
    op.create_index('ix_documents_content_hash', 'documents', ['content_hash'], unique=False)
    op.create_index('ix_documents_priority_date', 'documents', ['priority_date'], unique=False)
    op.create_index('ix_documents_published_at', 'documents', ['published_at'], unique=False)
    op.create_index('ix_documents_type', 'documents', ['document_type'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cursor_from', sa.String(length=255), nullable=True),
    sa.Column('cursor_to', sa.String(length=255), nullable=True),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_skipped', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('bytes_transferred', sa.BigInteger(), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_ingestion_runs_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs'))
    )
    op.create_index('ix_runs_source_started', 'ingestion_runs', ['source_id', 'started_at'], unique=False)
    op.create_table('source_coverage',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('coverage_start_date', sa.Date(), nullable=False),
    sa.Column('coverage_end_date', sa.Date(), nullable=True),
    sa.Column('coverage_confidence', sa.Float(), nullable=False),
    sa.Column('publication_lag_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_coverage_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', name=op.f('pk_source_coverage'))
    )
    op.create_table('technologies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=512), nullable=False),
    sa.Column('canonical_name_ru', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('embedding_model_version', sa.String(length=128), nullable=True),
    sa.Column('peer_group_id', sa.UUID(), nullable=True),
    sa.Column('openalex_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cpc_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ipc_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('arxiv_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('github_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('ontology_version', sa.String(length=64), nullable=False),
    sa.Column('first_observed_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['technologies.id'], name=op.f('fk_technologies_parent_id_technologies')),
    sa.ForeignKeyConstraint(['peer_group_id'], ['peer_groups.id'], name=op.f('fk_technologies_peer_group_id_peer_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technologies'))
    )
    op.create_index('ix_technologies_peer_group', 'technologies', ['peer_group_id'], unique=False)
    op.create_index('ix_technologies_status', 'technologies', ['status'], unique=False)
    op.create_table('cluster_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_run_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('cluster_label', sa.Text(), nullable=True),
    sa.Column('technology_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('membership_score', sa.Float(), nullable=False),
    sa.CheckConstraint('(technology_id IS NOT NULL) <> (document_id IS NOT NULL)', name=op.f('ck_cluster_memberships_exactly_one_member_ref')),
    sa.ForeignKeyConstraint(['cluster_run_id'], ['cluster_runs.id'], name=op.f('fk_cluster_memberships_cluster_run_id_cluster_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_cluster_memberships_document_id_documents')),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], name=op.f('fk_cluster_memberships_technology_id_technologies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cluster_memberships'))
    )
    op.create_index('uq_membership_document', 'cluster_memberships', ['cluster_run_id', 'cluster_id', 'document_id'], unique=True, postgresql_where=sa.text('document_id IS NOT NULL'))
    op.create_index('uq_membership_technology', 'cluster_memberships', ['cluster_run_id', 'cluster_id', 'technology_id'], unique=True, postgresql_where=sa.text('technology_id IS NOT NULL'))
    op.create_table('dead_letter_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=512), nullable=True),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], name=op.f('fk_dead_letter_queue_ingestion_run_id_ingestion_runs')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_dead_letter_queue_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dead_letter_queue'))
    )
    op.create_index('ix_dlq_unresolved', 'dead_letter_queue', ['source_id', 'resolved'], unique=False)
    op.create_table('document_change_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('source_revision', sa.String(length=255), nullable=True),
    sa.Column('previous_content_hash', sa.String(length=64), nullable=True),
    sa.Column('new_content_hash', sa.String(length=64), nullable=True),
    sa.Column('previous_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_change_events_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], name=op.f('fk_document_change_events_ingestion_run_id_ingestion_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_change_events'))
    )
    op.create_index('ix_change_events_document', 'document_change_events', ['document_id', 'occurred_at'], unique=False)
    op.create_table('document_metric_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('is_reconstructed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_metric_snapshots_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_metric_snapshots')),
    sa.UniqueConstraint('document_id', 'metric_name', 'observed_at', name='uq_doc_metric_observation')
    )
    op.create_index('ix_doc_metric_lookup', 'document_metric_snapshots', ['document_id', 'metric_name', 'observed_at'], unique=False)
    op.create_table('ingestion_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('stream', sa.String(length=128), nullable=False),
    sa.Column('cursor', sa.String(length=512), nullable=True),
    sa.Column('cursor_type', sa.String(length=32), nullable=False),
    sa.Column('last_successful_run_id', sa.UUID(), nullable=True),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_successful_run_id'], ['ingestion_runs.id'], name=op.f('fk_ingestion_checkpoints_last_successful_run_id_ingestion_runs')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_ingestion_checkpoints_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_checkpoints')),
    sa.UniqueConstraint('source_id', 'stream', name='uq_checkpoint_stream')
    )
    op.create_table('strategic_matrix',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matrix_version', sa.String(length=64), nullable=False),
    sa.Column('technology_id', sa.UUID(), nullable=True),
    sa.Column('technology_pattern', sa.String(length=512), nullable=True),
    sa.Column('dimension', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('approved_at', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 0 AND score <= 100', name=op.f('ck_strategic_matrix_matrix_score_range')),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], name=op.f('fk_strategic_matrix_technology_id_technologies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategic_matrix'))
    )
    op.create_index('ix_matrix_version', 'strategic_matrix', ['matrix_version', 'is_active'], unique=False)
    op.create_table('technology_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('technology_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=512), nullable=False),
    sa.Column('normalized_alias', sa.String(length=512), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('is_abbreviation', sa.Boolean(), nullable=False),
    sa.Column('source_of_alias', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], name=op.f('fk_technology_aliases_technology_id_technologies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technology_aliases')),
    sa.UniqueConstraint('technology_id', 'normalized_alias', name='uq_alias_per_technology')
    )
    op.create_index('ix_alias_normalized', 'technology_aliases', ['normalized_alias'], unique=False)
    op.create_table('technology_lineage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('technology_id', sa.UUID(), nullable=False),
    sa.Column('cluster_run_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('parent_technology_id', sa.UUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['cluster_run_id'], ['cluster_runs.id'], name=op.f('fk_technology_lineage_cluster_run_id_cluster_runs')),
    sa.ForeignKeyConstraint(['parent_technology_id'], ['technologies.id'], name=op.f('fk_technology_lineage_parent_technology_id_technologies')),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], name=op.f('fk_technology_lineage_technology_id_technologies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technology_lineage'))
    )
    op.create_index('ix_lineage_technology', 'technology_lineage', ['technology_id', 'valid_from'], unique=False)
    op.create_table('technology_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('technology_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('external_id', sa.String(length=512), nullable=True),
    sa.Column('external_name', sa.Text(), nullable=True),
    sa.Column('mapping_method', sa.String(length=32), nullable=False),
    sa.Column('mapping_score', sa.Float(), nullable=False),
    sa.Column('mapping_status', sa.String(length=32), nullable=False),
    sa.Column('score_components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mapping_version', sa.String(length=64), nullable=False),
    sa.Column('evidence_document_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('mapping_score >= 0 AND mapping_score <= 1', name=op.f('ck_technology_mappings_score_range')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_technology_mappings_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_document_id'], ['documents.id'], name=op.f('fk_technology_mappings_evidence_document_id_documents')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_technology_mappings_source_id_sources')),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], name=op.f('fk_technology_mappings_technology_id_technologies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technology_mappings')),
    sa.UniqueConstraint('technology_id', 'document_id', 'mapping_version', name='uq_mapping_per_version')
    )
    op.create_index('ix_mapping_document', 'technology_mappings', ['document_id'], unique=False)
    op.create_index('ix_mapping_status', 'technology_mappings', ['mapping_status'], unique=False)
    op.create_index('ix_mapping_technology', 'technology_mappings', ['technology_id'], unique=False)
    op.create_table('technology_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('technology_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('papers', sa.Integer(), nullable=False),
    sa.Column('preprints', sa.Integer(), nullable=False),
    sa.Column('patent_families', sa.Integer(), nullable=False),
    sa.Column('patent_applicants', sa.Integer(), nullable=False),
    sa.Column('rd_projects', sa.Integer(), nullable=False),
    sa.Column('companies', sa.Integer(), nullable=False),
    sa.Column('github_repos', sa.Integer(), nullable=False),
    sa.Column('github_activity', sa.Float(), nullable=False),
    sa.Column('github_contributors', sa.Integer(), nullable=False),
    sa.Column('citations', sa.Integer(), nullable=False),
    sa.Column('news_mentions', sa.Integer(), nullable=False),
    sa.Column('unique_authors', sa.Integer(), nullable=False),
    sa.Column('unique_institutions', sa.Integer(), nullable=False),
    sa.Column('cpc_diversity', sa.Integer(), nullable=False),
    sa.Column('source_family_count', sa.Integer(), nullable=False),
    sa.Column('metric_status', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_quality_score', sa.Float(), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], name=op.f('fk_technology_metrics_technology_id_technologies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technology_metrics')),
    sa.UniqueConstraint('technology_id', 'period_start', 'as_of_date', name='uq_metric_period_asof')
    )
    op.create_index('ix_metrics_technology_period', 'technology_metrics', ['technology_id', 'period_start'], unique=False)
    op.create_table('trend_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('technology_id', sa.UUID(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('claim_type', sa.String(length=64), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('source_doc_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('is_quantitative', sa.Boolean(), nullable=False),
    sa.Column('verifier_passed', sa.Boolean(), nullable=False),
    sa.Column('verifier_notes', sa.Text(), nullable=True),
    sa.Column('evidence_confidence', sa.Float(), nullable=False),
    sa.Column('llm_model_version', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('evidence_set_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], name=op.f('fk_trend_evidence_technology_id_technologies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trend_evidence'))
    )
    op.create_index('ix_evidence_technology', 'trend_evidence', ['technology_id', 'as_of_date'], unique=False)
    op.create_table('trend_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('technology_id', sa.UUID(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('novelty', sa.Float(), nullable=True),
    sa.Column('growth', sa.Float(), nullable=True),
    sa.Column('acceleration', sa.Float(), nullable=True),
    sa.Column('research', sa.Float(), nullable=True),
    sa.Column('patent', sa.Float(), nullable=True),
    sa.Column('citation', sa.Float(), nullable=True),
    sa.Column('market', sa.Float(), nullable=True),
    sa.Column('adoption', sa.Float(), nullable=True),
    sa.Column('cross_domain', sa.Float(), nullable=True),
    sa.Column('maturity', sa.Float(), nullable=True),
    sa.Column('maturity_stage', sa.String(length=32), nullable=True),
    sa.Column('emerging_score', sa.Float(), nullable=False),
    sa.Column('strategic_relevance', sa.Float(), nullable=True),
    sa.Column('strategic_priority', sa.Float(), nullable=True),
    sa.Column('evidence_confidence', sa.Float(), nullable=False),
    sa.Column('effective_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metric_status', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('peer_group_id', sa.UUID(), nullable=True),
    sa.Column('reference_population_size', sa.Integer(), nullable=True),
    sa.Column('scoring_version', sa.String(length=64), nullable=False),
    sa.Column('dataset_version', sa.String(length=64), nullable=False),
    sa.Column('ontology_version', sa.String(length=64), nullable=False),
    sa.Column('embedding_model_version', sa.String(length=128), nullable=True),
    sa.Column('cluster_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_run_id'], ['cluster_runs.id'], name=op.f('fk_trend_scores_cluster_run_id_cluster_runs')),
    sa.ForeignKeyConstraint(['peer_group_id'], ['peer_groups.id'], name=op.f('fk_trend_scores_peer_group_id_peer_groups')),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], name=op.f('fk_trend_scores_technology_id_technologies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trend_scores')),
    sa.UniqueConstraint('technology_id', 'as_of_date', 'scoring_version', name='uq_score_per_version')
    )
    op.create_index('ix_scores_asof_ets', 'trend_scores', ['as_of_date', 'emerging_score'], unique=False)
    op.create_index('ix_scores_technology', 'trend_scores', ['technology_id', 'as_of_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scores_technology', table_name='trend_scores')
    op.drop_index('ix_scores_asof_ets', table_name='trend_scores')
    op.drop_table('trend_scores')
    op.drop_index('ix_evidence_technology', table_name='trend_evidence')
    op.drop_table('trend_evidence')
    op.drop_index('ix_metrics_technology_period', table_name='technology_metrics')
    op.drop_table('technology_metrics')
    op.drop_index('ix_mapping_technology', table_name='technology_mappings')
    op.drop_index('ix_mapping_status', table_name='technology_mappings')
    op.drop_index('ix_mapping_document', table_name='technology_mappings')
    op.drop_table('technology_mappings')
    op.drop_index('ix_lineage_technology', table_name='technology_lineage')
    op.drop_table('technology_lineage')
    op.drop_index('ix_alias_normalized', table_name='technology_aliases')
    op.drop_table('technology_aliases')
    op.drop_index('ix_matrix_version', table_name='strategic_matrix')
    op.drop_table('strategic_matrix')
    op.drop_table('ingestion_checkpoints')
    op.drop_index('ix_doc_metric_lookup', table_name='document_metric_snapshots')
    op.drop_table('document_metric_snapshots')
    op.drop_index('ix_change_events_document', table_name='document_change_events')
    op.drop_table('document_change_events')
    op.drop_index('ix_dlq_unresolved', table_name='dead_letter_queue')
    op.drop_table('dead_letter_queue')
    op.drop_index('uq_membership_technology', table_name='cluster_memberships', postgresql_where=sa.text('technology_id IS NOT NULL'))
    op.drop_index('uq_membership_document', table_name='cluster_memberships', postgresql_where=sa.text('document_id IS NOT NULL'))
    op.drop_table('cluster_memberships')
    op.drop_index('ix_technologies_status', table_name='technologies')
    op.drop_index('ix_technologies_peer_group', table_name='technologies')
    op.drop_table('technologies')
    op.drop_table('source_coverage')
    op.drop_index('ix_runs_source_started', table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index('ix_documents_type', table_name='documents')
    op.drop_index('ix_documents_published_at', table_name='documents')
    op.drop_index('ix_documents_priority_date', table_name='documents')
    op.drop_index('ix_documents_content_hash', table_name='documents')
    op.drop_index('ix_documents_available_from', table_name='documents')
    op.drop_table('documents')
    op.drop_table('sources')
    op.drop_table('peer_groups')
    op.drop_table('model_versions')
    op.drop_index('ix_feedback_round', table_name='expert_feedback')
    op.drop_index('ix_feedback_object', table_name='expert_feedback')
    op.drop_table('expert_feedback')
    op.drop_table('cluster_runs')
    op.drop_index('ix_jobs_status', table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    # ### end Alembic commands ###
