"""v1.5: source freshness, three-tier scores, discovery candidates

Revision ID: 9af270dd6ca8
Revises: ff57f3ac56e7
Create Date: 2026-09-13 21:02:26.517387+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '9af270dd6ca8'
down_revision: str | None = 'ff57f3ac56e7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_freshness',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('indexing_lag_months', sa.Float(), nullable=True),
    sa.Column('indexing_lag_method', sa.String(length=64), nullable=True),
    sa.Column('observation_lag_p50_days', sa.Float(), nullable=True),
    sa.Column('observation_lag_p90_days', sa.Float(), nullable=True),
    sa.Column('observation_sample_size', sa.Integer(), nullable=False),
    sa.Column('update_frequency_hours', sa.Float(), nullable=True),
    sa.Column('is_backtestable', sa.Boolean(), nullable=False),
    sa.Column('backtest_note', sa.Text(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_freshness_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', name=op.f('pk_source_freshness'))
    )
    op.create_table('candidate_technologies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_run_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('suggested_name', sa.String(length=512), nullable=True),
    sa.Column('suggested_name_ru', sa.String(length=512), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('naming_model_version', sa.String(length=128), nullable=True),
    sa.Column('centroid', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('first_period', sa.Date(), nullable=True),
    sa.Column('last_period', sa.Date(), nullable=True),
    sa.Column('representative_document_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('semantic_coherence', sa.Float(), nullable=True),
    sa.Column('temporal_growth', sa.Float(), nullable=True),
    sa.Column('acceleration', sa.Float(), nullable=True),
    sa.Column('semantic_distance', sa.Float(), nullable=True),
    sa.Column('source_diversity', sa.Float(), nullable=True),
    sa.Column('cross_source_consistency', sa.Float(), nullable=True),
    sa.Column('volume_sufficiency', sa.Float(), nullable=True),
    sa.Column('discovery_score', sa.Float(), nullable=False),
    sa.Column('score_components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scoring_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('promoted_technology_id', sa.UUID(), nullable=True),
    sa.Column('nearest_technology_id', sa.UUID(), nullable=True),
    sa.Column('nearest_similarity', sa.Float(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_run_id'], ['cluster_runs.id'], name=op.f('fk_candidate_technologies_cluster_run_id_cluster_runs')),
    sa.ForeignKeyConstraint(['nearest_technology_id'], ['technologies.id'], name=op.f('fk_candidate_technologies_nearest_technology_id_technologies')),
    sa.ForeignKeyConstraint(['promoted_technology_id'], ['technologies.id'], name=op.f('fk_candidate_technologies_promoted_technology_id_technologies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_technologies')),
    sa.UniqueConstraint('cluster_run_id', 'cluster_id', name='uq_candidate_per_run')
    )
    op.create_index('ix_candidates_status_score', 'candidate_technologies', ['status', 'discovery_score'], unique=False)
    op.add_column(
        'technologies',
        # Существующие технологии вписаны в онтологию руками — значит seeded.
        sa.Column('origin', sa.String(length=32), nullable=False, server_default='seeded'),
    )
    op.add_column('technologies', sa.Column('discovered_at', sa.Date(), nullable=True))
    op.add_column('trend_scores', sa.Column('early_warning_score', sa.Float(), nullable=True))
    op.add_column('trend_scores', sa.Column('confirmed_score', sa.Float(), nullable=True))
    op.add_column('trend_scores', sa.Column('signal_delta', sa.Float(), nullable=True))
    op.add_column('trend_scores', sa.Column('signal_status', sa.String(length=64), nullable=True))
    op.add_column(
        'trend_scores',
        sa.Column(
            'detector_scores',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    op.add_column('trend_scores', sa.Column('change_point_date', sa.Date(), nullable=True))
    op.add_column('trend_scores', sa.Column('change_point_confidence', sa.Float(), nullable=True))
    op.add_column('trend_scores', sa.Column('temporal_novelty', sa.Float(), nullable=True))
    op.add_column('trend_scores', sa.Column('semantic_novelty', sa.Float(), nullable=True))
    op.add_column(
        'trend_scores',
        sa.Column(
            'signal_availability',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trend_scores', 'signal_availability')
    op.drop_column('trend_scores', 'semantic_novelty')
    op.drop_column('trend_scores', 'temporal_novelty')
    op.drop_column('trend_scores', 'change_point_confidence')
    op.drop_column('trend_scores', 'change_point_date')
    op.drop_column('trend_scores', 'detector_scores')
    op.drop_column('trend_scores', 'signal_status')
    op.drop_column('trend_scores', 'signal_delta')
    op.drop_column('trend_scores', 'confirmed_score')
    op.drop_column('trend_scores', 'early_warning_score')
    op.drop_column('technologies', 'discovered_at')
    op.drop_column('technologies', 'origin')
    op.drop_index('ix_candidates_status_score', table_name='candidate_technologies')
    op.drop_table('candidate_technologies')
    op.drop_table('source_freshness')
    # ### end Alembic commands ###
